### ISSUE TITLE
Can't build in K/Ubuntu 20.10

### ISSUE THREAD

**Issue by mescobal** [repos-holder/kdecoration2-kde2#2]
CMake Error at CMakeLists.txt:9 (find_package):
  By not providing "FindKDecoration2.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "KDecoration2", but CMake did not find one.

  Could not find a package configuration file provided by "KDecoration2" with
  any of the following names:

    KDecoration2Config.cmake
    kdecoration2-config.cmake

  Add the installation prefix of "KDecoration2" to CMAKE_PREFIX_PATH or set
  "KDecoration2_DIR" to a directory containing one of the above files.  If
  "KDecoration2" provides a separate development package or SDK, be sure it
  has been installed.

-- Configuring incomplete, errors occurred!

**Comment by dukzcry** [comment]
You need to install `libkdecorations2-dev` to fix that error.
Full list of dependencies `extra-cmake-modules qtbase5-dev libkf5coreaddons-dev libkdecorations2-dev`

**Comment by mescobal** [comment]
It worked!!!! Thanks a lot!!!! This decoration with Trinity Desktop Environmente TDE-classic icons and "plastique" application style and you're almost in kde 2.2 paradise!!!! Thanks again!

**Comment by dukzcry** [comment]
Great! You may also like this KDE2 application style for qtcurve engine https://store.kde.org/p/1214244/

**Comment by mescobal** [comment]
Wow!! Now in full "Kde2" mode!!! There's something very appealling in these retro themes (same with Mac System 7, 8 and 9). Thanks (again)!!
